### PR TITLE
nav menu stick to the top when scrolling

### PR DESCRIPTION
**Pull request by jienagu**
This PR is to fix the nav menu on the top of page when users scrolling the web site.

### CODE REVIEW

**Comment by jienagu** [comment]
Or somehow give users this option of sticky menu in case the webpage is too long. I am also thinking to add a Scroll Back To Top Button if users don't like the sticky menu... What do you think? :)

**Review by yihui — COMMENTED** [review]
Yes, I'd like to give users an option to configure it: they could either have a static header, a sticky header, or a scroll back button at the bottom. The option could be in `.Params.features` like other features. Thanks!

**Comment by jienagu** [comment]
Fantastic! Welcome to change in this PR! :)

**Comment by apreshill** [comment]
I love a good "scroll to top" in the footer. I added that with a caret symbol on <https://www.tidymodels.org/> (following <https://themes.gohugo.io/theme/academic/>). I can offer in a separate PR, but I don't see an HTML symbol I can use. This feature is mainly useful if you have a universally recognized symbol.

https://github.com/tidymodels/tidymodels.org/blob/606d8ba9256bd07c1e434b304eb9121622cb1676/layouts/partials/footer.html#L20-L26

**Comment by yihui** [comment]
@apreshill That symbol is straightforward to create via CSS, e.g., by rotating a square:

```html
<span class="caret"></span>
```

```css
.caret {
    display: inline-block;
    border-top: 2px solid;
    border-left: 2px solid;
    width: 1em;
    height: 1em;
    transform: rotate(45deg);
}
```

which gives you:

image

@jienagu On second thought, a menu item "Back to top" in the bottom menu might serve the purpose better in this case, because the bottom menu is purely text-based currently, and I don't know where to place an icon if we want to use an icon. The menu item is also dead easy to add in `config.yaml`:

```yaml
menu:
  footer:
    - name: Back to top
      url: "#"
```

Two lines of config. No need to involve any CSS or JS.

**Comment by yihui** [comment]
Oh I forgot to mention the most important problem on my mind: if the top menu is sticky, it will cover the TOC when the TOC is sticky at the top. We need a `top` value for the TOC, but the value is dynamic (the height of the top menu) so can't be set in CSS; JS can do it, and I'm not sure if it's worth the effort, although the effort is quite low.

**Comment by apreshill** [comment]
brilliant re: CSS solution! 🥕

**Comment by yihui** [comment]
Sticky menu implemented via e6c4e26. And "Back to top" via c53f4ad.

**Comment by yihui** [comment]
With 385e7c2 , the sticky menu will no longer cover the TOC.

**Comment by yihui** [comment]
Demo: https://prose.yihui.org/post/2020/11/10/r-markdown-demo/

**Pull request merged**
