### PR TITLE
multilingual support with i18n

### PR DESCRIPTION
**Pull request by pzhaonet**
This PR added the i18n module for multilingual support, with a demonstration for Chinese.

### CODE REVIEW

**Review by yihui — APPROVED** [review]
Great! Looks good to me at a first glance, and I'll take a closer look tomorrow. Thank you!

**Comment by pzhaonet** [comment]
Great! Note that some are not translated yet, including the "post" and "work" labels on the home page, the "Cards" and "Posts" titles on the sitemap page, and the "Contents" title on the TOC of each post. I just cannot find them in `layouts/`.

**Comment by lief-y** [comment]
> Great! Note that some are not translated yet, including the "post" and "work" labels on the home page, the "Cards" and "Posts" titles on the sitemap page, and the "Contents" title on the TOC of each post. I just cannot find them in `layouts/`.

It seems that Hugo uses the folder names to create the titles: "Posts" is generated from the folder name "post". You can see that by using Chinese for a folder name.

I guess this can be configured by modifying the template of Hugo-Prose.

**Comment by pzhaonet** [comment]
> It seems that Hugo uses the folder names to create the titles: "Posts" is generated from the folder name "post". You can see that by using Chinese for a folder name.

Thanks for the info. I tried this but got something unexpected. I renamed the folder `content/post` as `content/文章`, but the "post" label on the home page was still "post". Moreover, on the sitemap page, the list of posts was still there with a title "Posts", and I got one more list there with the title "文章s". Yes, the Chinese noun got a plural form.

**Comment by lief-y** [comment]
> > It seems that Hugo uses the folder names to create the titles: "Posts" is generated from the folder name "post". You can see that by using Chinese for a folder name.
> 
> Thanks for the info. I tried this but got something unexpected. I renamed the folder `content/post` as `content/文章`, but the "post" label on the home page was still "post". Moreover, on the sitemap page, the list of posts was still there with a title "Posts", and I got one more list there with the title "文章s". Yes, the Chinese noun got a plural form.

One way I can think of is to hack the templates list.html and sitemap.html. I forked your repository msg2020 and made changes in the forked version. I can make a pull request if that's okay with you.

**Comment by pzhaonet** [comment]
> I can make a pull request if that's okay with you.

Yes, please! It is wonderful!

**Pull request merged**
