### PR TITLE
Fonts

### PR DESCRIPTION
**Pull request by apreshill**
Hi @yihui,

One of the things I really liked about the Lithium theme (https://github.com/yihui/hugo-lithium) we used previously as the blogdown default theme was that it included some locally hosted fonts. I think the theme needs to ship with some custom fonts, mainly so motivated folks can figure out how to do this. They could of course do a font import, but I believe it is more accessible to locally host fonts. I grabbed a serif and sans serif font to test, see what you think:

https://sharp-colden-263590.netlify.app/

https://fonts.google.com/specimen/EB+Garamond

https://fonts.google.com/specimen/Alegreya+Sans

I'm not married to either of these specific fonts, but was trying to go for something that fit the theme. Let me know what you think!

### CODE REVIEW

**Review by yihui — COMMENTED** [review]
To me, fonts are the number one key to the appearance of a site, so this will be probably the most important decision to make in this project :) I'll need some time to think about it. For now, I just want to say that I'm all for changing the current default fonts (which I just blindly copied from XMin), but we'll see which specific fonts we want to use. Personally I tend to use system fonts unless all of them look ugly. I often use this website to help me find out which fonts are available on which OS: https://www.cssfontstack.com

**Comment by apreshill** [comment]
> To me, fonts are the number one key to the appearance of a site, so this will be probably the most important decision to make in this project

Same 😸  I may try a few more combos in separate branches and we can take our time!

**Comment by apreshill** [comment]
I should ask, are you open to adding locally hosted Google fonts? This is a common ask by users to be able to customize, and now with thematic support (https://rstudio.github.io/thematic/articles/fonts.html) and gt support (https://gt.rstudio.com/reference/google_font.html), showing how to use Google fonts will be especially helpful. If not, I won't spend more time on this though.

**Comment by yihui** [comment]
> I should ask, are you open to adding locally hosted Google fonts?

I prefer not adding them to this theme because 1) they would be extra dependencies for us to maintain, although they should rarely need to be maintained at all because they don't get updated frequently; 2) it's too hard to satisfy everyone's taste no matter how hard we try. I'd rather be neutral here, and use system fonts that at least don't look ugly. Then tell users how to change fonts. I separated the font customization from the main style precisely for this reason: https://github.com/yihui/hugo-prose/blob/master/static/css/fonts.css If users want to use other fonts, they provide their own `static/css/fonts.css` to override ours.

If necessary, we could provide a helper function to download the fonts and generate the CSS automatically. I guess someone must have done this in other packages. I have used this service before and I feel it's pretty good: https://google-webfonts-helper.herokuapp.com/fonts

**Comment by apreshill** [comment]
OK I'll keep my forks of the theme for teaching then.

**Pull request closed without merging**
